# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  name: drf-to-mkdoc
  version: "0.2.4"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/drf_to_mkdoc-${{ version }}.tar.gz
  sha256: 067e050dad7a260b653a5243877b529b6c81db46be238ca4cf79904ef46c0a9e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=80
    - wheel
    - setuptools-scm >=8.0
    - pip
  run:
    - python >=${{ python_min }},<4.0
    - django >=3.2,<6.0
    - djangorestframework >=3.12,<4.0
    - pyyaml >=6.0
    - drf-spectacular >=0.26.0
    - mkdocs >=1.4.0
    - mkdocs-material >=9.0.0
    #  mkdocs-material 9.6.20 has requirement click<8.2.2, but you have click 8.3.0.
    - click <8.2.2
    - python-coreapi >=2.3.0

tests:
  - python:
      imports:
        - drf_to_mkdoc
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Generate Markdown API docs from Django/DRF OpenAPI schema for MkDocs
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/shayestehhs/drf-to-mkdoc

extra:
  recipe-maintainers:
    - rxm7706
